CREATE TABLE CITIZENSHIP_CODE
(
    CITIZENSHIP_CODE VARCHAR(10)                            NOT NULL,
    LABEL                VARCHAR(50)                            NOT NULL,
    DESCRIPTION          VARCHAR(255)                           NOT NULL,
    DISPLAY_ORDER        NUMERIC   DEFAULT 1                    NOT NULL,
    EFFECTIVE_DATE       TIMESTAMP                              NOT NULL,
    EXPIRY_DATE          TIMESTAMP                              NOT NULL,
    LANGUAGE             VARCHAR(1),
    CREATE_USER          VARCHAR(32)                            NOT NULL,
    CREATE_DATE          TIMESTAMP DEFAULT CURRENT_TIMESTAMP    NOT NULL,
    UPDATE_USER          VARCHAR(32)                            NOT NULL,
    UPDATE_DATE          TIMESTAMP DEFAULT CURRENT_TIMESTAMP    NOT NULL,
    CONSTRAINT CITIZENSHIP_CODE_PK PRIMARY KEY (CITIZENSHIP_CODE)
);

INSERT INTO CITIZENSHIP_CODE (CITIZENSHIP_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
    VALUES ('C','Canadian','Canadian citizenship',10,
            to_date('2019-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
            to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS'),
            'SCHOLARSHIPS-API', CURRENT_TIMESTAMP,'SCHOLARSHIPS-API',CURRENT_TIMESTAMP);

INSERT INTO CITIZENSHIP_CODE (CITIZENSHIP_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE)
    VALUES ('O','Other','Other citizenship',20,
            to_date('2021-07-01 00:00:00','YYYY-MM-DD HH24:MI:SS'),
            to_date('2099-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS'),
            'SCHOLARSHIPS-API', CURRENT_TIMESTAMP,'SCHOLARSHIPS-API',CURRENT_TIMESTAMP);

