CREATE TABLE SCHOLARSHIPS_EVENT
(
    EVENT_ID      UUID                             NOT NULL,
    EVENT_PAYLOAD VARCHAR                          NOT NULL,
    EVENT_STATUS  VARCHAR(50)                        NOT NULL,
    EVENT_TYPE    VARCHAR(100)                       NOT NULL,
    SAGA_ID       UUID,
    EVENT_OUTCOME VARCHAR(100)                       NOT NULL,
    REPLY_CHANNEL VARCHAR(100),
    CREATE_USER   VARCHAR(100)                         NOT NULL,
    CREATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER   VARCHAR(100)                         NOT NULL,
    UPDATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SCHOLARSHIPS_EVENT_PK PRIMARY KEY (EVENT_ID)
);
CREATE INDEX SCHOLARSHIPS_EVENT_EVENT_STATUS_IDX ON SCHOLARSHIPS_EVENT (EVENT_STATUS);
CREATE INDEX SCHOLARSHIPS_EVENT_SAGA_ID_IDX ON SCHOLARSHIPS_EVENT (SAGA_ID);
CREATE INDEX SCHOLARSHIPS_EVENT_EVENT_TYPE_IDX ON SCHOLARSHIPS_EVENT (EVENT_TYPE);


CREATE TABLE SCHOLARSHIPS_SHEDLOCK
(
    NAME       VARCHAR(64),
    LOCK_UNTIL TIMESTAMP(3) NULL,
    LOCKED_AT  TIMESTAMP(3) NULL,
    LOCKED_BY  VARCHAR(255),
    CONSTRAINT SCHOLARSHIPS_SHEDLOCK_PK PRIMARY KEY (NAME)
);
COMMENT ON TABLE SCHOLARSHIPS_SHEDLOCK IS 'This table is used to achieve distributed lock between pods, for schedulers.';
